In [1]:
import numpy as np
image = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 2],
    [3, 0, 1, 2, 1],
    [2, 1, 3, 0, 0],
    [1, 2, 0, 1, 2]
])

image.shape

(5, 5)

In [2]:
kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])



# Define convolution operation
def convolve(image, kernel):
    image_h, image_w = image.shape
    kernel_h, kernel_w = kernel.shape
    output_h = image_h - kernel_h + 1
    output_w = image_w - kernel_w + 1
    output = np.zeros((output_h, output_w))

    for i in range(output_h):
        for j in range(output_w):
            output[i, j] = np.sum(image[i:i+kernel_h, j:j+kernel_w] * kernel)

    return output

# Apply the convolution
output = convolve(image, kernel)
print("Convolution Output:\n", output)

Convolution Output:
 [[  0.   0.  -6.]
 [  6.   3.  -3.]
 [  3. -10.   6.]]


#Padding

1. Padding: Zero-padding is added to the image to control the spatial dimensions of the output.
2. Stride: Controls how much the filter moves at each step. A stride of 1 means the filter moves one pixel at a time.
3. Convolution with Padding and Stride: The output is now controlled by the padding and stride, allowing us to maintain or reduce the spatial dimensions of the output.

In [3]:
# Adding padding
def pad_image(image, pad):
    return np.pad(image, pad, mode='constant', constant_values=0) # zero padding

pad_image(image, 1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 0],
       [0, 0, 1, 2, 3, 2, 0],
       [0, 3, 0, 1, 2, 1, 0],
       [0, 2, 1, 3, 0, 0, 0],
       [0, 1, 2, 0, 1, 2, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [4]:
# Modify convolution to include stride and padding
def convolve_with_padding_and_stride(image, kernel, stride=1, padding=0):
    if padding > 0:
        image = pad_image(image, padding)

    image_h, image_w = image.shape
    kernel_h, kernel_w = kernel.shape
    output_h = (image_h - kernel_h) // stride + 1
    output_w = (image_w - kernel_w) // stride + 1
    output = np.zeros((output_h, output_w))

    for i in range(0, output_h * stride, stride):
        for j in range(0, output_w * stride, stride):
            output[i // stride, j // stride] = np.sum(
                image[i:i+kernel_h, j:j+kernel_w] * kernel
            )

    return output

In [7]:
# Define a simple 5x5 grayscale image
image = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 2],
    [3, 0, 1, 2, 1],
    [2, 1, 3, 0, 0],
    [1, 2, 0, 1, 2]
])

# Apply the convolution with padding and stride
padded_output = convolve_with_padding_and_stride(image, kernel, stride=1, padding=1)
print("Padded Convolution Output:\n", padded_output)

Padded Convolution Output:
 [[ -2.  -3.  -8.   7.  -2.]
 [  5.   0.   0.  -6.  -3.]
 [-10.   6.   3.  -3.   0.]
 [ -3.   3. -10.   6.   3.]
 [  0.  -6.   6.  -2.  -7.]]


In [8]:
def maxpooling(image, pool_size, stride):
    rows, cols = image.shape
    n1 = (rows - pool_size) // stride + 1
    n2 = (cols - pool_size) // stride + 1

    output = np.zeros((n1, n2))

    for i in range(0, n1* stride, stride):
        for j in range(0, n2*stride, stride):
            output[i//stride, j//stride] = np.max(image[i:i+pool_size, j:j+pool_size])
    
    return output

In [10]:
import numpy as np

# Define a simple 5x5x3 RGB image (3 channels)
image = np.array([
    [[1, 0, 2], [2, 1, 1], [3, 2, 0], [0, 1, 1], [1, 0, 2]],
    [[0, 1, 0], [1, 0, 1], [2, 2, 2], [3, 1, 3], [2, 0, 1]],
    [[3, 0, 2], [0, 1, 0], [1, 0, 1], [2, 2, 2], [1, 0, 0]],
    [[2, 1, 1], [1, 0, 2], [3, 3, 1], [0, 1, 0], [0, 2, 1]],
    [[1, 2, 2], [2, 1, 0], [0, 0, 1], [1, 2, 2], [2, 1, 1]]
])

# Define a 3x3x3 filter (kernel) for each channel (RGB)
kernel = np.array([
    [[0, 1, 0], [1, -1, 1], [0, 1, 0]],
    [[1, 0, 1], [0, -1, 0], [1, 0, 1]],
    [[0, 1, 0], [1, 1, 1], [0, 1, 0]]
])

# Convolution operation
def convolve_rgb(image, kernel):
    image_h, image_w, image_c = image.shape
    kernel_h, kernel_w, kernel_c = kernel.shape
    output_h = image_h - kernel_h + 1
    output_w = image_w - kernel_w + 1
    output = np.zeros((output_h, output_w, 1))

    for k in range(image_c):  # Apply the convolution for each channel
        for i in range(output_h):
            for j in range(output_w):
                output[i, j] += np.sum(image[i:i+kernel_h, j:j+kernel_w, k] * kernel[:, :, k])
    return output

# Apply the convolution
output = convolve_rgb(image, kernel)
print("Convolution Output:\n", output)
output.shape

Convolution Output:
 [[[ 9.]
  [14.]
  [14.]]

 [[18.]
  [15.]
  [14.]]

 [[11.]
  [ 9.]
  [12.]]]


(3, 3, 1)

In [14]:
# Implementing with keras
import tensorflow as tf

from tensorflow.keras import layers, models


input_shape = (100, 100, 3)

model = models.Sequential()

model.add(layers.Input(shape = input_shape))

model.add(layers.Conv2D(16, (3,3), padding='same', strides=1, activation='relu'))
model.add(layers.MaxPool2D(pool_size=(2, 2), strides = 2))

model.add(layers.Conv2D(32, (3,3), padding='same', strides=1, activation='relu'))
model.add(layers.MaxPool2D(pool_size=(2, 2), strides = 2))

model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 100, 100, 16)   │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 50, 50, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 50, 50, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 25, 25, 32)     │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,088 (19.88 KB)

 Trainable params: 5,088 (19.88 KB)

 Non-trainable params: 0 (0.00 B)